### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ShireGrin** [mtpham99/gtowizard_scrape_public#1]
Hello, thank you for the upload

Now, long story short, i found this repo:
https://github.com/bupticybee/TexasSolver

It's an open source solver, made with qt creator. I found that the .txt files in your zips work in TexasSolver.

The problem is i don't understand your folder structure or how it works, i would really like to use the ranges but 
![image](https://github.com/user-attachments/assets/a1dd81de-8055-42fa-a33b-ca8331810263)

Could you help me please?

**Comment by ShireGrin** [comment]
Also due to TexasSolver being free, i'm worried  or don't know if the solutions "work" similarly to other solvers.

Maybe we could try inputting the same flop and bet ranges and pot/effective pot so we can confirm it works the same?
I just don't have the money to pay for solvers and given that this one is open source i  may even try to upgrade it but I just want to make sure the core logic works

**Comment by mtpham99** [comment]
> Hello, thank you for the upload
> 
> Now, long story short, i found this repo: https://github.com/bupticybee/TexasSolver
> 
> It's an open source solver, made with qt creator. I found that the .txt files in your zips work in TexasSolver.
> 
> The problem is i don't understand your folder structure or how it works, i would really like to use the ranges but ![image](https://private-user-images.githubusercontent.com/53883062/378122909-a1dd81de-8055-42fa-a33b-ca8331810263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNzQ0NzgsIm5iZiI6MTcyOTM3NDE3OCwicGF0aCI6Ii81Mzg4MzA2Mi8zNzgxMjI5MDktYTFkZDgxZGUtODA1NS00MmZhLWEzM2ItY2E4MzMxODEwMjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDIxNDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGY1MzE2MTE0NDFjNWQyMGJhMjk5OTdjZjUyZDBmMzFjMjhmNTI3NDVlZWM2ZDllMTQwYjBlN2UzYWRiNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.65IfEK4kqKNn_7m9kSzXX3Cl2yWwQlnhIm2daZzNDnA)
> 
> Could you help me please?

I explain a little in the readme [here](https://github.com/mtpham99/gtowizard_scrape_public?tab=readme-ov-file#12-directory-structure). In your example, the files correspond to small blind (SB) and big blind's (BB) range after the following preflop actions:

1. Action folds to SB (i.e. UTG, UTG1, LJ, HJ, CO, and BTN folded)
2. SB opens to 3.5bb
3. BB calls
4. Preflop action complete



> Also due to TexasSolver being free, i'm worried or don't know if the solutions "work" similarly to other solvers.
> 
> Maybe we could try inputting the same flop and bet ranges and pot/effective pot so we can confirm it works the same? I just don't have the money to pay for solvers and given that this one is open source i may even try to upgrade it but I just want to make sure the core logic works

As for TexasSolver, you'd have to check with its developer to better understand how it works. But to clarify, the ranges I have provided are ***preflop*** ranges. If you wanted to compare TexasSolver's (postflop) solves with GTOWizard's solutions, you'd have to replicate the same exact settings GTOWizard uses (stack sizes, bet sizes on each street, rake settings, etc.). You'd probably find more useful advice regarding this test by asking TexasSolver users.

**Comment by ShireGrin** [comment]
Okay i understand so BB.txt file will contain the expected range on BB and viceversa. Thank you, so this doesn't really tell you what to "do". It tells you the expected ranges on the players, that i can use for the solver post flop then. Thanks again!
